word_list = ['kullan', 'korunak', 'kocaman', 'kitap', 'çözmek', 'güçlü', 'hızlıca', 'hayaller', 'yanmak', 'koltuk',
             'zorlamak', 'kitaplık', 'üzüntü', 'çalışma', 'zafer', 'aydınlık', 'bilmek', 'geçmiş', 'mühendis', 'eller',
             'temiz', 'yemek', 'kıyafet', 'bilen', 'sorunsuz', 'çekmek', 'yaşamak', 'kapıdan', 'tehlike', 'akarsu',
             'işlemek', 'seviyor', 'başarılar', 'dostluk', 'derinlik', 'temizlik', 'yıkamak', 'kalabalık',
             'bakmak', 'yaklaş', 'çizmek', 'sürmek', 'silmek', 'deniz', 'tarihçi', 'saklamak', 'beklemek', 'elemek',
             'anlama', 'gökyüzü', 'kurtar', 'gelecek', 'güvenmek', 'yürümek', 'yüzeysel', 'konuşma', 'okumak',
             'çalışmak', 'kaybolmak', 'bahçev', 'soğukkan', 'sabırlı', 'yüzmek', 'yanlış', 'gülmek',
             'sağlık', 'kalmak', 'düşünce', 'bitirmek', 'durmak', 'ağlamak', 'çevirmek', 'birikim', 'doğmak',
             'yıldız', 'başlamak', 'teknolog', 'soğuk', 'yolluk', 'tekrar', 'büyüme', 'özlemek', 'kalıcı', 'güzel',
             'koşmak', 'sesli', 'gerçek', 'deneme', 'beyaz', 'yıkılmak', 'başarı', 'dayanmak', 'oynayan', 'kiremit',
             'gelenek', 'güvenli', 'akıllı', 'umutsuz','sakatat', 'bilgisayar', 'projeksiyon', 'tiramisu',
             'trileçe', 'otostop', 'telefon', 'tren', 'ankara', 'gölbaşı', 'kitaplık', 'kalemlik',
             'masmavi', 'başlangıç', 'öğretmen', 'elbise', 'hayvanat', 'kardeşlik', 'gözlükçü', 'kütüphane', 'fabrika',
             'manzara', 'serbest', 'üniversite', 'düzenleme', 'evcilik', 'hastalık', 'güvenlik', 'çiçeklik', 'gezegen'
             ]